# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI to Docker Hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
          
    - name: Check Out Repo 
      uses: actions/checkout@v2
    
    - name: Build with Maven
      run: mvn -U clean package -Dmaven.test.skip=true && cp -rf ./llcf-server/target/llcf-server-0.0.1-SNAPSHOT.jar ./ && rm -rf ./llcf-client && rm -rf ./llcf-common && rm -rf ./llcf-example && rm -rf ./llcf-server && rm -rf ./pom.xml && ls
        
    - name: Build Docker Image
      id: buildAndPushImage
      uses: risfeng/docker-image-build-push-action@v1.0
      with:
        registry_url: 'ccr.ccs.tencentyun.com'
        namespaces: 'tcb-1083895682-xnfy'
        repository_name: 'llcf'
        user_name: 1083895682
        password: 1355@lIN
        image_version: 'v1.0'
        docker_file: './Dockerfile'

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
