# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI to Docker Hub

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
          
    - name: Check Out Repo 
      uses: actions/checkout@v2
    
    - name: Build with Maven
      run: mvn -U clean package -Dmaven.test.skip=true && cp -rf ./llcf-server/target/llcf-server-0.0.1-SNAPSHOT.jar ./ && rm -rf ./llcf-client && rm -rf ./llcf-common && rm -rf ./llcf-example && rm -rf ./llcf-server && rm -rf ./pom.xml && ls

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Docker Toolkit
      uses: hericlesme/Dockerflow@0.0.1
      with:
        name: build_and_push
        username: 1083895682
        password: 1355@lIN
        registry: ccr.ccs.tencentyun.com
        dockerfile: ./Dockerfile
        workdir: ./
        cache: false
        tag_names: tcb-1083895682-xnfy/llcf

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
